---
name: apache-remote-proxy
director_uuid: d79b8bdc-238f-43b5-8d0c-f0ac9d02148e

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

compilation:
  cloud_properties:
    name: random
  network: cf3
  reuse_compilation_vms: true
  workers: 6

resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: cf3
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

releases:
- name: apache
  version: latest

networks:
- name: cf3
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: []

jobs:
- name: httpd
  templates:
  - name: apache
    release: apache
  instances: 1
  resource_pool: small_z1
  networks:
  - name: cf3
    static_ips : 10.244.2.6
  properties:
    httpd:
      port: 8081
      username: admin
      password: admin
      use_remote_proxy: true
      remote_proxy: http://admin:admin@10.244.2.2:8080
